### ISSUE TITLE
Look at HV timing info for small valence

### ISSUE THREAD

**Issue by gonuke** [pshriwise/dissertation#11]
All the HV timing plots go to valence levels far beyond those seen in the wild.  It may be interesting to look at the results in the lower left corner and see what narrative emerges.

**Comment by pshriwise** [comment]
I pulled out some data for smaller valence cases. The ray fire timing still increases an order of magnitude. There are some interesting patterns in there, but I'm not sure it changes things that much.

![moab_small_v](https://user-images.githubusercontent.com/4563941/43751433-7a9c198e-99c2-11e8-91b9-2b28058bc204.png)

![mpbvh_small_v](https://user-images.githubusercontent.com/4563941/43751432-7a7f0cfe-99c2-11e8-85a4-e37702b56718.png)

**Comment by gonuke** [comment]
What if you only go to 500?

**Comment by pshriwise** [comment]
![moab_small_v](https://user-images.githubusercontent.com/4563941/43843694-bf2b63ee-9aed-11e8-82d6-9527343d922b.png)

![mpbvh_small_v](https://user-images.githubusercontent.com/4563941/43843692-bf197f6c-9aed-11e8-9054-33b6bc8d80bb.png)

Adjusted the bounds to better match the data on the second plot..

**Comment by gonuke** [comment]
Doesn't change much in the trends and performance model, and MPBVH is always much better!

**Comment by pshriwise** [comment]
Indeed :) It was good to see. Going to take a quick look at these for the adaptive MPBVH case just to see if anything strange shows up, but I think it looks alright. 

Wondering if I should include these somewhere in the document for completeness. What do you think?

**Comment by pshriwise** [comment]
![mpbvh_small_v_refine](https://user-images.githubusercontent.com/4563941/43882237-9c164176-9b74-11e8-82cf-5bef3ab2f154.png)

**Comment by gonuke** [comment]
I think it makes sense to add these with a brief discussion about the fact that these are more representative of the real world, but less useful for exploring algorithmic scaling... and then a sentence or two of conclusion.

**Comment by pshriwise** [comment]
![moab_small_v_refine](https://user-images.githubusercontent.com/4563941/43905176-18e140ca-9bb6-11e8-904b-12737f43b528.png)
![mpbvh_small_v_refine](https://user-images.githubusercontent.com/4563941/43905177-18f127d8-9bb6-11e8-88cf-c47631c168c3.png)

**Comment by gonuke** [comment]
Does a linear color scale make more sense here?

-- ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ --
Paul P.H. Wilson
608-263-0807<tel:608-263-0807>
paul.wilson@wisc.edu<mailto:paul.wilson@wisc.edu>
419 Engineering Research Bldg<x-apple-data-detectors://0/3>
1500 Engineering Dr, Madison, WI 53706<x-apple-data-detectors://0/3>
calendar: http://go.wisc.edu/pphw-cal

Grainger Professor of Nuclear Engineering
Computational Nuclear Engineering Research Group

[Sent from my iPhone]

On Aug 9, 2018, at 09:25, Patrick Shriwise <notifications@github.com<mailto:notifications@github.com>> wrote:


[moab_small_v_refine]<https://user-images.githubusercontent.com/4563941/43905176-18e140ca-9bb6-11e8-904b-12737f43b528.png>
[mpbvh_small_v_refine]<https://user-images.githubusercontent.com/4563941/43905177-18f127d8-9bb6-11e8-88cf-c47631c168c3.png>

**Comment by pshriwise** [comment]
Yeah it does, thanks. Updating...

**Comment by pshriwise** [comment]
**Linear Scale**
![moab_small_v_refine](https://user-images.githubusercontent.com/4563941/43906026-e6135050-9bb7-11e8-8af1-4bd22dddf45c.png)
![mpbvh_small_v_refine](https://user-images.githubusercontent.com/4563941/43906035-e964a9d4-9bb7-11e8-8f82-7e05d02f3afd.png)

**Comment by pshriwise** [comment]
**Automatic Limits** (linear scale also)
![moab_small_v_refine_free_lim](https://user-images.githubusercontent.com/4563941/43906065-fd909396-9bb7-11e8-9d0c-bea4b3fc5366.png)
![mpbvh_small_v_refine_free_lim](https://user-images.githubusercontent.com/4563941/43906064-fd7c2e60-9bb7-11e8-9ce0-74b095ba25f7.png)

**Comment by gonuke** [comment]
Maybe from [0, 4E-6] on both?

Paul


-- ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ --
Paul P.H. Wilson.  (he/him/his)
Grainger Professor of Nuclear Engineering
608-263-0807<tel:608-263-0807>
paul.wilson@wisc.edu<mailto:paul.wilson@wisc.edu>
443 Engineering Research Bldg
1500 Engineering Dr, Madison, WI 53706<x-apple-data-detectors://18/2>
calendar: http://go.wisc.edu/pphw-cal

Computational Nuclear Engineering Research Group
cnerg.engr.wisc.edu<http://cnerg.engr.wisc.edu/>

[sent from my iPad]

On Aug 9, 2018, at 09:38, Patrick Shriwise <notifications@github.com<mailto:notifications@github.com>> wrote:


Automatic Limits (linear scale also)
[moab_small_v_refine_free_lim]<https://user-images.githubusercontent.com/4563941/43906065-fd909396-9bb7-11e8-9d0c-bea4b3fc5366.png>
[mpbvh_small_v_refine_free_lim]<https://user-images.githubusercontent.com/4563941/43906064-fd7c2e60-9bb7-11e8-9ce0-74b095ba25f7.png>
