### ISSUE TITLE
Extended discussion of DAGMC model watertightness

### ISSUE THREAD

**Issue by pshriwise** [pshriwise/dissertation#15]
There is a request for more in-depth discussion about the definition of watertightness or a "fully sealed" model in DAGMC. Right now I refer to Brandon Smith's paper on `make_watertight`, but I could include a more explicit discussion in the background chapter. What do you think @gonuke?

**Comment by gonuke** [comment]
Can you point me to where you discuss this now?  I don't think there needs to be a lot of discussion of that here.  What's the context for the request?  I suppose the single precision conversion could be seen as undermining watertightness?

**Comment by pshriwise** [comment]
I discuss it most explicitly in the section on limitations of the EmDAG system in Section 4.2.4. 

The main reason I see for this discussion that it explains why we expect to see zero lost particles and why that may not be true for all models. In hindsight, this is probably better suited for the background section (as Tim suggested) if I want to establish this condition for certain models.

I can also see another option where I state that DAGMC didn't lose particles and the EmDAG system did as a comparative result, end of story, but I think that the watertightness discussion is more thorough.

I'd say the reduced precision conversion undermines the tracking algorithm more than the watertightness condition. In theory, single precision particles could be tracked robustly because the model is still technically watertight.

**Comment by pshriwise** [comment]
I'm not sure if we reached a conclusion on this, but after re-reading what I have on watertightness I think it is sufficient in the context of this work.
