### ISSUE TITLE
Distance Limit comparison for SDF

### ISSUE THREAD

**Issue by pshriwise** [pshriwise/dissertation#3]
"You should compare the execution time savings from SDF to that from distance limit in the DAGMC/MOAB-based traversal. I'm guessing here that it's an easy thing to turn off the distance limit, so this should be a minor code modification."

**Comment by pshriwise** [comment]
- [x] ITER
- [x] nTOF
- [x] SHINE
- [x] SHINE*
- [x] SNS

**Comment by pshriwise** [comment]
| Model | Reg | Dist Limit | Results match    | No Lost Particles |
|----------|----------|--------------|-----------------------|----------------|
| SNS    | 31.76 | 30.32    |  :heavy_check_mark: | :heavy_check_mark:  |
| SHINE | 432.52 | 371.00 | :heavy_check_mark: |  :heavy_check_mark: |
| SHINE* | 77.70 | 39.93 | :heavy_check_mark: | :heavy_check_mark: |
| nTOF |  117.2 | 53.57 | :heavy_check_mark: | :heavy_check_mark: |
| ITER|  5139.99 | 1204.8 | :x: | :x:|


**Note:** ITER's time is an extrapolation from 1E6 histories, where the standard simulation runs w/ 1E7 histories. The simulation using the distance limit optimization becomes stuck in an infinite loop on history 5675911.

**Comment by gonuke** [comment]
Do any of these have your updates?  or is `Reg` indicating pre-Shriwise MOAB/DAGMC?

**Comment by pshriwise** [comment]
Nope. No updates. Reg is pre-me MOAB/DAGMC.

**Comment by pshriwise** [comment]
This was added to the document in #21

**Comment by pshriwise** [comment]
This was resolved in PR #21
