### ISSUE TITLE
Context for Translation-Based Methods

### ISSUE THREAD

**Issue by pshriwise** [pshriwise/dissertation#5]
"You should mention in the background section the translation-based approaches to speed up MC on CAD-derived models. It would also be helpful if you could give order-of-magnitude runtimes for MC on those models, though I understand that data may be hard to come by and will not be directly comparable to the runtimes for your method."

IMO this belongs in the background in it's own section.

**Comment by pshriwise** [comment]
Note to self: This is briefly mentioned in Chapter 1 and should be tied to the location of this section elsewhere in the document.

**Comment by pshriwise** [comment]
I think this is actually covered in chapter 2 at the end of the CSG section. Can you verify @gonuke?

I'm not sure that I have a way to make fair comparisons of these approaches, particularly for the models I've been using for production demonstrations. Though I'm open to exploring ways to get that information if necessary.

**Comment by gonuke** [comment]
I don't think it is in scope to get new/relevant performance data.  You can quote (very) old performance data, but improvements have been ongoing on both sides of that coin.

I could suggest some additional words about human vs. computer effort, but nothing really citable....

**Comment by pshriwise** [comment]
I'd honestly rather claim it as a separate method altogether given the simplifications needed to perform the translation process.

I'd be happy to hear any suggestions you have!

**Comment by pshriwise** [comment]
Still hung up on this. Wondering if I shouldn't ping Tim T and see if he maybe missed the mention of a couple of these tools. It certainly wasn't an extensive list of these tools and I didn't go into detail regarding file formats or results, but I think awareness of other methods is all that is required here. I'm not trying to compare methods, only improve an existing one.

**Comment by pshriwise** [comment]
(backpedals...) Reading that section again, I only mention those tools in the context of visualization and geometry repair. I don't describe them as tools used to provide simulation-ready input. I'll review this tonight and come up with a better description.

**Comment by gonuke** [comment]
Yeah - that's probably not the best way to mention them anyway...

Maybe remove their mention from the end of 2.2, and add a paragraph at the top of 2.4 about tools that exist to convert from CAD to CSG:
* a number of them exist (history includes a few more than MCAM/McCAD)
* they have some limitations (limited surface representation = CAD modification)
* they have some benefits (no source code modification[1] & faster runtime)
* you can refer to past efforts to compare them head-2-head with DAGMC being 2-4x slower

[1] I just noticed that I don't think you ever discuss how DAGMC gets coupled to MC physics codes
