### ISSUE TITLE
Native Code Parallelism Paradigms

### ISSUE THREAD

**Issue by pshriwise** [pshriwise/dissertation#6]
A section on this should be added to discuss why memory limits for our application are more of a concern than they are in rendering which allow for much larger memory limits associated with the geometry as Prof. Sifakis alluded to.

**Comment by gonuke** [comment]
Somewhere there needs to be some discussion of why we didn't pursue remeshing of the HV regions.  Perhaps it fits here, perhaps it fits in #8 ?  Or maybe somewhere else.

**Comment by pshriwise** [comment]
I think my plan will be to add some background on memory usage in parallel MC and ~allude to~ reference it later in the high-valence chapter when this comes up.

**Comment by pshriwise** [comment]
Addressed in PR #17
