### ISSUE TITLE
Edge-length Faceting Tolerance Performance

### ISSUE THREAD

**Issue by pshriwise** [pshriwise/dissertation#8]
After the post-defense discussion today, I'm not sure that doing this globally is the right answer and faceting some of the production models with this scheme could lead to memory requirements larger than my workstation allows - which would mean I'd need another similar hardware set to run them on (and I'd need to install the software stack there as well) 

Uncertain how to handle this. Any suggestions @gonuke?

**Comment by pshriwise** [comment]
I realized today that another complication with this is the use of the CUBIT 12.2 workflow to generate the benchmark models I’ve been using. This was done before we were aware of the legal issues but I cannot use that’s same workflow anymore to generate length tolerance models.

I could use Trelis, but it wouldn’t necessarily be a fair comparison..

**Comment by gonuke** [comment]
hmmm... that is an issue...

You could use Trelis to generate a nominal model as well as an edge-length model and look at the ratios (with a comment about workflow versions, etc)....

**Comment by pshriwise** [comment]
Seems messy, but it might be the only way at this point. I think only providing ratios would be the way to go there. I'll also likely have to manage the edge-length for the ITER model to keep it a manageable size for my machine.

**Comment by pshriwise** [comment]
<table> 
  <thead>
    <tr>
        <th> Model </th> 
        <th colspan=2> Triangles </th>
        <th colspan=2> Sealed </th>
        <th colspan=2> DAGMC</th>
        <th colspan=2> MPBVH</th>
        <th colspan=2> Result Match (DAGMC:MPBVH) </th>
    </tr>
 </thead>

  <tbody>
    <tr>
       <td> </td>
       <td> FT </td>
       <td> ET </td>
       <td> FT </td>
       <td> ET </td>
       <td> Timing (FT/LT) </td>
       <td> Result Match (FT:LT) </td>
       <td> Timing (FT/LT) </td>
       <td> Result Match (FT:LT) </td>
       <td> FT </td>
       <td> LT </td>
    </tr>
    <tr>
      <td> FNG </td> 
      <td> 1168862 </td>
      <td> 1757746 </td>
      <td> :heavy_check_mark:  </td>
      <td> :heavy_check_mark:  </td>
      <td> 1.04 </td>
      <td align="center"> :x: </td>
      <td> 1.32 </td>
      <td align="center"> :x: </td>
      <td> :heavy_check_mark: </td>
      <td> ✔️ </td>
    </tr>
    <tr>
      <td> UWNR </td>
      <td> 3352162 </td>
      <td> 10134095 </td>
      <td> :heavy_check_mark:  </td>
      <td> :heavy_check_mark:  </td>
      <td> 0.996 </td>
      <td align="center"> :x: </td>
      <td> 1.006 </td>
      <td align="center"> :x: </td>
      <td> ✔️  </td>
      <td> ❌  </td>
    </tr>
    <tr>
      <td> ATR </td>
      <td> 4947941 </td>
      <td> 29669005 </td>
      <td> :heavy_check_mark:  </td>
      <td> :heavy_check_mark:  </td>
      <td> 0.665 </td>
      <td align="center"> :x: </td>
      <td> 0.829 </td>
      <td align="center"> ❌  </td>
      <td> ✔️  </td>
      <td>  ✔️ </td>
    </tr>
    <tr>
      <td> ITER </td>
      <td> 39631955 </td>
      <td> 42388877 </td>
      <td> :x: </td>
      <td> :x: </td>
      <td> 0.954 </td>
      <td align="center"> ❌  </td>
      <td> 1.31 </td>
      <td align="center"> ❌  </td>
      <td> ✔️ </td>
      <td> ✔️ </td>
    </tr>
  </tbody>
</table>

~~UWNR meshtallies were **very different** (statistically different)~~ (resolved)

All models with edge-length tolerance were faceted with a tolerance ~ 1/10 the total scale length of the model.

**Comment by pshriwise** [comment]
Even faceting the UWNR model is taking up nearly all the memory on my machine. I'm concerned about ATR/ITER going forward...

**Comment by pshriwise** [comment]
Resolved by #26
