### ISSUE TITLE
Add OBB-only Ray Fire timings for MPBVH in Dissertation Writeup

### ISSUE THREAD

**Issue by pshriwise** [pshriwise/dissertation#9]
Tim T. mentioned that these were not in the thesis document and he's right that they should be added for completion in the consideration fo AABBs vs. OBBs.

**Comment by pshriwise** [comment]
Turns out I actually did include this. I thought I had, and I should've been more confident in that during the defense. They are located in Section 5.5.3.

**Comment by gonuke** [comment]
Maybe one issue is that this needs to be compared against Fig 4.3 (or so) and that is pretty far back.  I wonder if it’s worth repeating Fig 4.3-ish here for comparison’s sake.

**Comment by gonuke** [comment]
Could also add some kind of (quasi-)quantitative comparison of the speeds in the text.  “... OBB trees are between X and Y times slower than AABB trees... “

**Comment by pshriwise** [comment]
Hrmm I'm not sure about copying the entirety of 4.3, but I think the comparison you described would be good. Maybe I could duplicate only the MPBVH AABB ray tracing results from Figure 4.3 here.

**Comment by pshriwise** [comment]
This is addressed in #13.
